Creates a Yarn Workspace & utilizes React on the client side
coforma/co-regulations-gov pull request #17
Opened 2021-12-16 18:30 UTC by scottymeyers

I suspect that by utilizing React, we'll be able to tackle all of the desired features quicker, such as searching and sorting of the results.

I'd love some confirmation that this works as expected, as is a straight forward experience, and worthwhile!

2021-12-16 20:43 UTC, infinityplusone commented
Looking

2021-12-16 21:05 UTC, scottymeyers commented
@infinityplusone make sure to pull in the latest once more.

2021-12-17 14:01 UTC, infinityplusone requested changes
First off: "Files changed: 2,085" — Who are you, @jaredcunha?

More importantly, can you add a `.gitignore` back and make sure it includes the `.env` and output files (and anything other stuff that might show up in the root)?

2021-12-17 14:03 UTC, scottymeyers commented
> First off: "Files changed: 2,085" — Who are you, @jaredcunha?
> 
> More importantly, can you add a `.gitignore` back and make sure it includes the `.env` and output files (and anything other stuff that might show up in the root)?

That stuff is all located in each of the packages now.

2021-12-17 14:20 UTC, infinityplusone commented
> That stuff is all located in each of the packages now.

Saw that, but would still like one at the root for the stupid files like `.DS_Store`.

2021-12-17 14:24 UTC, scottymeyers commented
> > That stuff is all located in each of the packages now.
> 
> Saw that, but would still like one at the root for the stupid files like `.DS_Store`.

Done.

2021-12-17 14:26 UTC, infinityplusone commented
One other thing I just noticed... The output files for the CLI version are created in `./packages/server/`.

1. That feels like the wrong place for them
2. I can't imagine how someone would figure that location out
3. I think it might make sense to create an output folder (at the root) for them and create filenames based on document ID and execution time
4. The messaging when it's done should tell the user where they are (and what they are called)
5. That folder should be added to the `.gitignore`

2021-12-17 17:27 UTC, infinityplusone requested changes
Couple files got added that shouldn't be there. Also, need to check for and create the `output` directory if it doesn't exist:
```sh
An error occured while writing JSON Object to File.
[Error: ENOENT: no such file or directory, open '.../co-regulations-gov/output/NHTSA-2021-0001-output.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.../co-regulations-gov/output/NHTSA-2021-0001-output.json'
}
An error occured while converting the JSON to CSV.
[Error: ENOENT: no such file or directory, open '.../co-regulations-gov/output/NHTSA-2021-0001-output.csv'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.../co-regulations-gov/output/NHTSA-2021-0001-output.csv'
}

```

2021-12-17 17:27 UTC, infinityplusone commented on packages/server/output/NHTSA-2021-0001-output.csv
> +commentOn,commentOnDocumentId,duplicateComments,address1,address2,agencyId,city,category,comment,country,displayProperties,docAbstract,docketId,documentType,email,fax,field1,field2,fileFormats,firstN
Pretty sure this file shouldn't be included.

2021-12-17 17:27 UTC, infinityplusone commented on packages/server/package.json
> +{
Pretty sure this file shouldn't be included.

2021-12-17 17:29 UTC, scottymeyers commented
> Couple files got added that shouldn't be there. Also, need to check for and create the `output` directory if it doesn't exist

But it's in the repo, no? I can't tell because I can't view files changes because its overloaded.

2021-12-17 17:31 UTC, infinityplusone commented
> > Also, need to check for and create the `output` directory if it doesn't exist
> 
> But it's in the repo, no? I can't tell because I can't view files changes because its overloaded.

It's in the repo inside of `./packages/server/`, but it *correctly* tries to write to `./output/`, which isn't in the repo.

2021-12-17 17:32 UTC, scottymeyers commented
I included it in the main directory, but it looks like it was removed. I cannot tell because I can't see the files changed.

2021-12-17 19:17 UTC, merged